# https://gitlab.com/mattia.basaglia/glaxnimate/-/ci/lint
default:
    before_script:
        - apt-get update -qq
        - apt-get install -y cmake qtbase5-dev libpython3-dev python3-pip zlib1g-dev qttools5-dev-tools qttools5-dev libpotrace-dev libavformat-dev libswscale-dev libavcodec-dev libavutil-dev

variables:
    DEBIAN_FRONTEND: noninteractive
    GIT_SUBMODULE_STRATEGY: recursive


.shared_windows_runners:
    tags:
        - shared-windows
        - windows
        - windows-1809

pages:
    image: ubuntu:latest
    stage: deploy
    script:
        - apt-get install -y doxygen graphviz g++ python3-distutils git
        - mkdir -p build
        - cd build
        - cmake ..
        - make doxygen
        - make docs_depends_install
        - make docs
    after_script:
        - mv build/docs/site public
        - mv build/coverage public/coverage
        - mv build/doxygen/html public/doxygen
    artifacts:
        paths:
            - public
    when: always
    only:
        - master
    needs: ["linux:test"]


linux:test:
    image: ubuntu:latest
    stage: build
    script:
        - pip3 install gcovr
        - mkdir build
        - cd build
        - cmake ..
        - make tests_coverage
    artifacts:
        paths:
            - build/coverage
    when: always

linux:build:
    image: ubuntu:latest
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_CXX_FLAGS="-Werror -pedantic"
        - make VERBOSE=1
    when: always

linux:deb:
    image: ubuntu:latest
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake .. -DCPACK_DEBIAN_FILE_NAME=glaxnimate.deb -DVERSION_SUFFIX="deb-$CI_COMMIT_SHORT_SHA"
        - make
        - make translations
        - cpack -G DEB
        - sha1sum glaxnimate.deb >checksum.txt
    artifacts:
        paths:
            - build/glaxnimate.deb
            - build/checksum.txt
            - build/CMakeCache.txt
    when: always

linux:aur:
    image: archlinux:latest
    stage: deploy
    only:
        - tags
        - release
        - pre-release
    before_script:
        - pacman -Sy
        - pacman -S --noconfirm git base-devel fakeroot vim openssh namcap xorg-xauth cmake qt5-base python zlib hicolor-icon-theme potrace ffmpeg qt5-tools
    script:
        - mkdir -p build
        - cd build
        - cmake ..
        # Settings
        - PROJECT_VERSION="$(../deploy/get_version.sh CMakeCache.txt)"
        - git config --global user.name "Glaxnimate CI"
        - git config --global user.email "glaxnimate-ci@mattbas.org"
        # Update glaxnimate-git
        - PACK_NAME=glaxnimate-git
        - GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i $AUR_SSH_KEY" git clone ssh://aur@aur.archlinux.org/$PACK_NAME.git
        - cd $PACK_NAME
        - sed -i -e "s/pkgver=.*/pkgver=$PROJECT_VERSION/" PKGBUILD
        - namcap PKGBUILD
        - makepkg --printsrcinfo > .SRCINFO
        - git commit -am "Update to version $PROJECT_VERSION"
        - GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i $AUR_SSH_KEY" git push
        - cd ..

linux:appimage:
    image: ubuntu:16.04
    stage: build
    before_script:
        - apt-get update -qq
        - apt-get install -y libpython3-dev python3-pip software-properties-common desktop-file-utils wget zlib1g-dev libpotrace-dev zip
        - add-apt-repository ppa:beineri/opt-qt-5.15.0-xenial -y
        - add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - apt update -qq
        - apt-get install -y qt515base qt515tools qt515translations libgl1-mesa-dev g++-9 qt515svg
        - pip3 install cmake
        - echo libav from source
        - apt-get install -y git build-essential nasm pkg-config
        - git clone https://github.com/FFmpeg/FFmpeg.git
        - cd FFmpeg/
        - ./configure --disable-static --enable-shared
        - make -j2
        - make install
        - cd ..
    script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 -DCMAKE_PREFIX_PATH=/opt/qt515/lib/cmake/Qt5LinguistTools/ -DVERSION_SUFFIX="appimage-$CI_COMMIT_SHORT_SHA"
        - make -j2
        - make translations
        - make install DESTDIR=AppDir >/dev/null
        - mkdir AppDir/usr/lib
        - cp -r /usr/lib/python3.* AppDir/usr/lib
        - cp ../deploy/app_run.sh AppDir/AppRun
        - chmod a+x AppDir/AppRun
        - cp AppDir/usr/share/glaxnimate/glaxnimate/glaxnimate.desktop AppDir
        - cp AppDir/usr/share/glaxnimate/glaxnimate/images/glaxnimate.png AppDir
        - wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        - ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract
        - ls -l /usr/local/lib/
        - ldd AppDir/usr/bin/glaxnimate
        - LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH" ldd AppDir/usr/bin/glaxnimate
        - PATH="/opt/qt515/bin/:$PATH" LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH" VERSION=dev ./squashfs-root/AppRun AppDir/glaxnimate.desktop -extra-plugins=iconengines,platformthemes,imageformats -appimage
        - mv glaxnimate-dev-x86_64.AppImage glaxnimate-x86_64.AppImage
        - sha1sum glaxnimate-x86_64.AppImage >checksum.txt
        - if [ -n "$BUTLER_API_KEY" ] ;
            then
                version="$(../deploy/get_version.sh CMakeCache.txt)" ;
                wget https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default ;
                unzip default ;
                chmod a+x butler ;
                ./butler push "glaxnimate-x86_64.AppImage" "MattBas/glaxnimate:linux-beta" --userversion "$version" ;
            fi
    artifacts:
        paths:
            - build/glaxnimate-x86_64.AppImage
            - build/checksum.txt
    when: always

#mxe:build:
    #image: mattbas/mxe-qt5:latest
    #stage: build
    #before_script:
    #script:
        #- mkdir build
        #- cd build
        #- x86_64-w64-mingw32.shared.posix-cmake .. -DCMAKE_INSTALL_PREFIX=/ -DVERSION_SUFFIX="win-$CI_COMMIT_SHORT_SHA"
        #- make
        #- make translations
        #- make install DESTDIR=glaxnimate >/dev/null
        #- /mxedeployqt/mxedeployqt --mxepath "/mxe" --mxetarget x86_64-w64-mingw32.shared.posix glaxnimate/bin/
        #- cp external/Qt-Color-Widgets/libQtColorWidgets.dll glaxnimate/bin/
        #- cp ../deploy/glaxnimate.bat glaxnimate
        #- zip -r glaxnimate-x86_64.zip glaxnimate >/dev/null
        #- sha1sum glaxnimate-x86_64.zip >checksum.txt
    #artifacts:
        #paths:
            #- build/glaxnimate-x86_64.zip
            #- build/checksum.txt
    #when: always

tarball:
    stage: build
    before_script:
    script:
        - rm -rf .git
        - cd ..
        - tar -caf /tmp/glaxnimate-src.tar.gz "$(basename "$CI_PROJECT_DIR")"
        - cd "$CI_PROJECT_DIR"
        - mv /tmp/glaxnimate-src.tar.gz .
        - sha1sum glaxnimate-src.tar.gz >checksum.txt
    artifacts:
        paths:
            - glaxnimate-src.tar.gz
            - checksum.txt

release:
    stage: deploy
    before_script:
        - apt-get update -qq
        - apt-get install -y python3-pip
        - pip3 install requests
    script:
        - ./deploy/make_release.py
        - ./deploy/gitlab_upload.py --copy release/MacOs/glaxnimate.dmg        $CI_COMMIT_TAG/MacOs/glaxnimate.dmg
        - ./deploy/gitlab_upload.py --copy release/MacOs/checksum.txt          $CI_COMMIT_TAG/MacOs/checksum.txt
        - ./deploy/gitlab_upload.py --copy release/Win/glaxnimate-x86_64.zip   $CI_COMMIT_TAG/Win/glaxnimate-x86_64.zip
        - ./deploy/gitlab_upload.py --copy release/Win/checksum.txt            $CI_COMMIT_TAG/Win/checksum.txt
    dependencies:
        - linux:test
        - linux:appimage
        - linux:deb
    only:
        - tags
    when: manual

linux:snap_tag:
    #image: snapcore/snapcraft:stable
    image: mattbas/snapcraft:latest
    stage: deploy
    only:
        - tags
    dependencies:
    needs: []
    before_script:
        - apt-get update -qq
        - apt-get install -y python3-pip
        - apt remove cmake
        - pip3 install cmake
    script:
        - test -n "$SNAPCRAFT_LOGIN_FILE"
        - test -f "$SNAPCRAFT_LOGIN_FILE"
        - mkdir -p build
        - cd build
        - cmake .. -DSNAP_IS_SUCH_A_PAIN=ON -DVERSION_SUFFIX="" || true
        - ls -lah .
        - cd ..
        - mkdir snap
        - cp build/snapcraft.yaml snap
        - snapcraft
        - snapcraft login --with "$SNAPCRAFT_LOGIN_FILE"
        - snapcraft upload --release=stable glaxnimate_*.snap

linux:snap_beta:
    #image: snapcore/snapcraft:stable
    image: mattbas/snapcraft:latest
    stage: deploy
    only:
        - master
        - pre-release
    dependencies:
    needs: []
    before_script:
        - apt-get update -qq
        - apt-get install -y python3-pip
        - apt remove cmake
        - pip3 install cmake
    script:
        - test -n "$SNAPCRAFT_LOGIN_FILE"
        - test -f "$SNAPCRAFT_LOGIN_FILE"
        - mkdir -p build
        - cd build
        - cmake .. -DSNAP_IS_SUCH_A_PAIN=ON -DVERSION_SUFFIX="snap-$CI_COMMIT_SHORT_SHA" || true
        - ls -lah .
        - cd ..
        - mkdir snap
        - cp build/snapcraft.yaml snap
        - snapcraft
        - snapcraft login --with "$SNAPCRAFT_LOGIN_FILE"
        - snapcraft upload --release=beta glaxnimate_*.snap

.pypi_build:
    stage: build
    script:
        - python3 --version
        - mkdir build
        - cd build
        - cmake ..
        - make glaxnimate_python_depends_install
        - make glaxnimate_python
    artifacts:
        paths:
            - build/py_module/build/lib/

linux:pypi_3.8:
    image: ubuntu:20.04
    extends: .pypi_build
    only:
        - master
        - release
        - tags

linux:pypi_3.9:
    image: ubuntu:21.04
    extends: .pypi_build
    only:
        - master
        - release
        - tags

linux:pypi_deploy:
    image: ubuntu:latest
    stage: deploy
    needs: ["linux:pypi_3.8", "linux:pypi_3.9"]
    dependencies:
        - linux:pypi_3.8
        - linux:pypi_3.9
    script:
        - python3 --version
        - mkdir -p build
        - cd build
        - cmake .. -DVERSION_SUFFIX="git.`date +%Y%m%d%H%M%S`.$CI_COMMIT_BRANCH.$CI_COMMIT_SHORT_SHA"
        - make glaxnimate_python_depends_install
        - ls py_module/build/lib
        - make glaxnimate_python_wheel
        - python3 -m twine upload py_module/dist/*.whl --repository-url https://gitlab.com/api/v4/projects/19921167/packages/pypi --verbose
    only:
        - master
        - release
        - prerelease
    environment:
        name: Gitlab PyPI


linux:pypi_deploy_tag:
    image: ubuntu:latest
    stage: deploy
    needs: ["linux:pypi_3.8", "linux:pypi_3.9"]
    dependencies:
        - linux:pypi_3.8
        - linux:pypi_3.9
    script:
        - python3 --version
        - mkdir -p build
        - cd build
        - cmake ..
        - make glaxnimate_python_depends_install
        - ls py_module/build/lib
        - make glaxnimate_python_wheel
        - make glaxnimate_python_upload
    environment:
        name: PyPI
    only:
        - tags

#windows:build:
    #extends:
        #- .shared_windows_runners
    #stage: build
    #before_script:
        #- choco feature enable -n allowGlobalConfirmation
        #- choco install msys2
        #- refreshenv
    #script:
        #- mkdir build
        #- cd build
        #- $env:CHERE_INVOKING='yes'  # Preserve the current working directory
        #- $env:MSYSTEM='MINGW64' # Start a 64 bit Mingw environment
        #- C:\tools\msys64\usr\bin\bash -lc "../deploy/win_build.sh 2>&1"
    #artifacts:
        #paths:
            #- build/glaxnimate-x86_64.zip
            #- build/checksum.txt
    #timeout: 3 hours
