default:
    before_script:
        - apt-get update -qq
        - apt-get install -y cmake qtbase5-dev libpython3-dev git python3-pip qttools5-dev-tools zlib1g-dev qttools5-dev-tools qttools5-dev
        - git submodule update --init --recursive

variables:
    DEBIAN_FRONTEND: noninteractive

pages:
    image: ubuntu:latest
    stage: deploy
    script:
        - apt-get install -y doxygen graphviz g++ python3-distutils
        - mkdir -p build
        - cd build
        - cmake ..
        - make doxygen
        - make docs_depends_install
        - make docs
    after_script:
        - mv build/docs/site public
        - mv build/coverage public/coverage
        - mv build/docs/html public/doxygen
    artifacts:
        paths:
            - public
    when: always
    only:
        - master
    needs: ["linux:test"]


linux:test:
    image: ubuntu:latest
    stage: build
    script:
        - pip3 install gcovr
        - mkdir build
        - cd build
        - cmake ..
        - make tests_coverage
    artifacts:
        paths:
            - build/coverage
    when: always

linux:build:
    image: ubuntu:latest
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make
    when: always

linux:deb:
    image: ubuntu:latest
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DCPACK_DEBIAN_FILE_NAME=glaxnimate.deb
        - make
        - make translations
        - cpack -G DEB
        - sha1sum glaxnimate.deb >checksum.txt
    artifacts:
        paths:
            - build/glaxnimate.deb
            - build/checksum.txt
    when: always

linux:appimage:
    image: ubuntu:16.04
    stage: build
    before_script:
        - apt-get update -qq
        - apt-get install -y libpython3-dev git python3-pip software-properties-common desktop-file-utils wget zlib1g-dev
        - add-apt-repository ppa:beineri/opt-qt-5.15.0-xenial -y
        - add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - apt update -qq
        - apt-get install -y qt515base qt515tools qt515translations libgl1-mesa-dev g++-9
        - pip3 install cmake
        - git submodule update --init --recursive
    script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 -DCMAKE_PREFIX_PATH=/opt/qt515/lib/cmake/Qt5LinguistTools/
        - make
        - make translations
        - make install DESTDIR=AppDir
        - cp AppDir/usr/share/glaxnimate/glaxnimate/glaxnimate.desktop AppDir
        - wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        - ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract
        - PATH="/opt/qt515/bin/:$PATH" VERSION=dev ./squashfs-root/AppRun AppDir/glaxnimate.desktop -extra-plugins=iconengines,platformthemes/libqgtk3.so -appimage
        - mv glaxnimate-dev-x86_64.AppImage glaxnimate-x86_64.AppImage
        - sha1sum glaxnimate-x86_64.AppImage >checksum.txt
    artifacts:
        paths:
            - build/glaxnimate-x86_64.AppImage
            - build/checksum.txt
    when: always

mxe:build:
    image: mattbas/mxe-qt5:latest
    stage: build
    before_script:
        - git submodule update --init --recursive
    script:
        - mkdir build
        - cd build
        - x86_64-w64-mingw32.shared.posix-cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/
        - make
        - make translations
        - make install DESTDIR=glaxnimate >/dev/null
        - /mxedeployqt/mxedeployqt --mxepath "/mxe" --mxetarget x86_64-w64-mingw32.shared.posix glaxnimate/bin/
        - cp external/Qt-Color-Widgets/libQtColorWidgets.dll glaxnimate/bin/
        - cp ../deploy/glaxnimate.bat glaxnimate
        - zip -r glaxnimate-x86_64.zip glaxnimate >/dev/null
        - sha1sum glaxnimate-x86_64.zip >checksum.txt
    artifacts:
        paths:
            - build/glaxnimate-x86_64.zip
            - build/checksum.txt
    when: always
