pages:
    stage: deploy
    before_script:
        - apt-get update -y
        - apt-get install -y cmake qtbase5-dev doxygen graphviz
        - git submodule update --init --recursive
    script:
        - echo TODO
    after_script:
        - mkdir public
        - mv build/coverage public/coverage
    artifacts:
        paths:
            - public
    when: always
    only:
        - master
    needs: ["linux:test"]


linux:test:
    stage: build
    before_script:
        - apt-get update -y
        - apt-get install -y cmake qtbase5-dev python-pip
        - pip install gcovr
        - git submodule update --init --recursive
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make tests_coverage
    artifacts:
        paths:
            - build/coverage
    when: always


linux:build:
    stage: build
    before_script:
        - apt-get update -y
        - apt-get install -y cmake qtbase5-dev
        - git submodule update --init --recursive
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make
    when: always

