default:
    before_script:
        - apt-get update -y
        - apt-get install -y cmake qtbase5-dev libpython3-dev git libqt5svg5-dev python3-pip curl qttools5-dev-tools
        - git submodule update --init --recursive

variables:
    DEBIAN_FRONTEND: noninteractive

pages:
    image: ubuntu:latest
    stage: deploy
    script:
        - apt-get install -y doxygen graphviz g++ python3-distutils
        - mkdir -p build
        - cd build
        - cmake ..
        - make doxygen
        - make docs_depends_install
        - make docs
    after_script:
        - mv build/docs/site public
        - mv build/coverage public/coverage
        - mv build/docs/html public/doxygen
    artifacts:
        paths:
            - public
    when: always
    only:
        - master
    needs: ["linux:test"]


linux:test:
    stage: build
    script:
        - pip3 install gcovr
        - mkdir build
        - cd build
        - cmake ..
        - make tests_coverage
    artifacts:
        paths:
            - build/coverage
    when: always


linux:build:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make AppImage
    artifacts:
        paths:
            - build/glaxnimate-x86_64.AppImage
    when: always

