# https://config.travis-ci.com/explore
language: cpp
stages:
    - build
jobs:
    include:
      - name: "Mac Tag"
        if: tag IS present
        stage: build
        os: osx
        osx_image: xcode11.3
        before_install:
            - brew install coreutils ed findutils gawk gnu-sed gnu-tar grep make
            - export PATH="$(echo /usr/local/opt/*/libexec/gnubin | tr ' ' :):$PATH"
            - ./deploy/mac_build.sh deps
        script:
            - ./deploy/mac_build.sh build
            - # PyPI
            - if [ "$TRAVIS_BRANCH" != macbuild ] ; then cmake .. -DVERSION_SUFFIX="" ; fi
            - ./deploy/mac_build.sh pypi
        after_success:
            - echo "-----BEGIN OPENSSH PRIVATE KEY-----" >privkey
            - chmod 600 privkey
            - set +x; echo "$SSH_PRIV_KEY" >>privkey
            - echo "-----END OPENSSH PRIVATE KEY-----" >>privkey
            - ./deploy/mac_build.sh deploy "$TRAVIS_BRANCH" "-i $PWD/privkey"
            - # Upload PyPI
            - cd ..
            - make glaxnimate_python_upload
      - name: "Mac branch"
        if: branch = macbuild OR branch = release
        stage: build
        os: osx
        osx_image: xcode11.3
        before_install:
            - brew install coreutils ed findutils gawk gnu-sed gnu-tar grep make
            - export PATH="$(echo /usr/local/opt/*/libexec/gnubin | tr ' ' :):$PATH"
            - ./deploy/mac_build.sh deps
        script:
            - ./deploy/mac_build.sh build
            - # PyPI
            - ./deploy/mac_build.sh pypi
        after_success:
            - echo "-----BEGIN OPENSSH PRIVATE KEY-----" >privkey
            - chmod 600 privkey
            - set +x; echo "$SSH_PRIV_KEY" >>privkey
            - echo "-----END OPENSSH PRIVATE KEY-----" >>privkey
            - ./deploy/mac_build.sh deploy "$TRAVIS_BRANCH" "-i $PWD/privkey"
