# https://config.travis-ci.com/explore
language: cpp
stages:
    - build
jobs:
    include:
      - name: "Mac"
        stage: build
        os: osx
        # compiler: gcc
        before_install:
            - brew list cmake || brew install cmake
            - brew list qt || brew install qt
            - brew list python || brew install python
            # - brew upgrade gcc@10 || true
            - brew list makeicns || brew install makeicns
            # - export CXX="$(brew list gcc | grep -F bin/g++ | sed 's/.*\///')"
            # - export CC="$(brew list gcc | grep -E "bin/gcc-[0-9]" | sed 's/.*\///')"
            # - echo $CXX
            # - $CXX --version
        script:
            - mkdir build
            - cd build
            - cmake .. -DQt5_DIR="$(brew --prefix qt)/lib/cmake/Qt5" -DVERSION_SUFFIX="mac-${TRAVIS_COMMIT::8}"
            - make
            - makeicns -512 ../data/images/glaxnimate.png -out glaxnimate.icns
            - cpack -G Bundle
        after_success:
            - mv Glaxnimate-*.dmg glaxnimate.dmg
            - shasum -a 1 glaxnimate.dmg >checksum.txt
            - ../deploy/bintray_upload.sh Dev glaxnimate.dmg "$TRAVIS_BRANCH/MacOs/glaxnimate.dmg"
            - ../deploy/bintray_upload.sh Dev checksum.txt "$TRAVIS_BRANCH/MacOs/checksum.txt"
