site_name: Glaxnimate Documentation
site_description: Glaxnimate is a simple and fast vector graphics animation program.
copyright: Copyright (C) 2020 Glaxnimate Contributors.
theme:
    name: cinder
    custom_dir: theme
    highlightjs: false
repo_url: https://gitlab.com/mattia.basaglia/glaxnimate
edit_uri: -/edit/master/docs/docs
markdown_extensions:
    - fontawesome_markdown
nav:
    - index.md
    - 'User Interface':
        - ui/index.md
    - 'Contributing':
        - contributing/index.md
        - "Readme": contributing/read_me.md
        - contributing/documentation.md
    - links.md
