name: Build
on: [push, workflow_dispatch, pull_request]
jobs:
    macos:
        runs-on: macOS-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: recursive
            - name: Install Deps
              run: |
                brew install coreutils ed findutils gawk gnu-sed gnu-tar grep make
                export PATH="$(echo /usr/local/opt/*/libexec/gnubin | tr ' ' :):$PATH"
                ./deploy/mac_build.sh deps
            - name: Build
              run: |
                export PATH="$(echo /usr/local/opt/*/libexec/gnubin | tr ' ' :):$PATH"
                ./deploy/mac_build.sh build "mac-${GITHUB_SHA:0:8}"
            - name: Build Python
              run: |
                export PATH="$(echo /usr/local/opt/*/libexec/gnubin | tr ' ' :):$PATH"
                ./deploy/mac_build.sh pypi
            # Artifacts are always zipped, even if you only have 1 file... Just adding them so it's easier to verify them
            - name: Artifact checksum.txt
              uses: actions/upload-artifact@v2
              with:
                name: glaxnimate-mac
                path: |
                    build/checksum.txt
                    build/glaxnimate.dmg
                    build/py_module/dist/
            - name: Upload Artifacts
              if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/github' }}
              env:
                SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
                BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
              run: |
                echo "$SSH_PRIV_KEY" >>privkey
                chmod 600 privkey
                branch="${GITHUB_REF#refs/*/}"
                export PATH="$(echo /usr/local/opt/*/libexec/gnubin | tr ' ' :):$PATH"
                ./deploy/mac_build.sh deploy "$branch" "-i $PWD/privkey"
    windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: msys2 {0}
        steps:
            - name: Setup msys2
              uses: msys2/setup-msys2@v2
              with:
                path-type: strict
                update: true
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: recursive
            - name: Install Deps
              run: |
                ./deploy/win_build.sh deps
            - name: Build
              run: |
                 ./deploy/win_build.sh build "win-${GITHUB_SHA:0:8}"
            - name: Build Python
              run: |
                ./deploy/win_build.sh pypi
            # Artifacts are always zipped, even if you only have 1 file... Just adding them so it's easier to verify them
            - name: Artifact checksum.txt
              uses: actions/upload-artifact@v2
              with:
                name: glaxnimate-win
                path: |
                    build/checksum.txt
                    build/glaxnimate-x86_64.zip
                    build/py_module/dist/
            - name: Upload Artifacts
              if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/github' }}
              env:
                SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
                BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
              run: |
                echo "$SSH_PRIV_KEY" >>privkey
                chmod 600 privkey
                branch="${GITHUB_REF#refs/*/}"
                export PATH="$(echo /usr/local/opt/*/libexec/gnubin | tr ' ' :):$PATH"
                ./deploy/win_build.sh deploy "$branch" "-i $PWD/privkey"
