name: PyPI Release
on:
    push:
        tags:
            - '*'
jobs:
    macos:
        runs-on: macOS-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: recursive
            - name: Install Deps
              run: |
                brew install coreutils ed findutils gawk gnu-sed gnu-tar grep make
                export PATH="$(echo /usr/local/opt/*/libexec/gnubin | tr ' ' :):$PATH"
                ./deploy/mac_build.sh deps
            - name: Build Python
              run: |
                export PATH="$(echo /usr/local/opt/*/libexec/gnubin | tr ' ' :):$PATH"
                ./deploy/win_build.sh configure ""
                ./deploy/mac_build.sh pypi
            - name: Upload Pypi
              env:
                TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
                TWINE_USERNAME: __token__
              run: |
                cd build
                make glaxnimate_python_upload
    windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: msys2 {0}
        steps:
            - name: Setup msys2
              uses: msys2/setup-msys2@v2
              with:
                path-type: strict
                update: true
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: recursive
            - name: Install Deps
              run: |
                ./deploy/win_build.sh deps
            - name: Build Python
              run: |
                ./deploy/win_build.sh configure ""
                ./deploy/win_build.sh pypi
            - name: Upload Pypi
              env:
                TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
                TWINE_USERNAME: __token__
              run: |
                cd build
                mingw32-make.exe glaxnimate_python_upload

